[short="A Letter of Elizabeth Webb"]
== A Letter From Elizabeth Webb to Anthony William Boehm

Worthy friend,--

The kind respect you showed me, when in London,
has laid me under an obligation wherein I find my mind drawn
to communicate to you in the openings of divine love;
on which I must desire your favourable construction, as I am almost a stranger to you.
What I have to write, has been on my mind these several weeks, in that pure,
innocent love in which is the communion of saints.
I have no learned method in which to deliver my religious experience,
either by word or writing, but plainly and simply as the Spirit of Truth directs:
and I being the weaker vessel too, have the more need to beg to be excused.
I shall not write from notions and speculations; I look on such things as unsafe,
and I know they are many times unsound:
but I shall write a small part of what I have gone through,
and what my soul has tasted of the good word of life, which is near;
that we may have fellowship together in God the Father of our spirits,
and in his Son Jesus Christ our Lord;
whom my soul has known both in mercy and in judgment, to the mortifying,
in a good degree, the fallen and corrupt nature, and to the purifying of my heart so far,
as that I can say to his praise, I do not see him through particular forms, sects,
party impressions, or any such thing.
No, my dear friend, I never sought after the Lord in these ways,
nor for any of these ends; but I sought after him in my young years for salvation,
and I still seek to him for the perfect restoration of my soul in him.
I have nothing of my own to boast of, unless it be weakness and infirmities;
but desire to rejoice in the cross of Christ,
by which I am crucified to the world in a good degree, and the world to me;
so that I can say, I die daily.

And as touching the fondness for education, religious profession and conversation,
these things have cast no mist before my eyes.
I can see, own and love the image of my Lord and Saviour in any sort of profession,
if the soul has been educated in the heavenly university or school of Christ.
Nevertheless, we cannot see God in, or have fellowship with all sorts of conduct;
that of the wicked is as if there was no God; "`God is not in all their thoughts.`"
And such as despise the image of the meek, humble Jesus,
and will follow none of his precepts, nor his self-denying example, while they are here,
the Lord will hereafter despise their image:
for they shall have an image according to the seed
or spirit in which they lay down their body:
every seed shall have its own body in the resurrection of the just and the unjust,
and everyone shall receive his own sentence.

You well observe that sin, self-love, self-will, etc.,
contract the soul into a very narrow compass;
but the love of God breaks down all those walls of selfishness by which
the soul is hedged in and restrained from universal love and benignity.
This is very true; but there are those who will not receive our love as it is in Jesus:
nevertheless, some have felt towards such,
the flowings of the love and compassion of Him, who "`would not the death of a sinner,
but rather that all would return to Him, repent and live.`"
I am a witness for the Lord,
that the shedding abroad of his love over the inhabitants of this nation,
has been like showers of rain in the spring time.
I well remember that I told a Friend in London,
I felt the divine extendings of the love of God so to flow to the people,
as I walked in the streets of the city,
that I could have freely published the salvation of God, which is near,
and his righteousness which is ready to be revealed, in the public places of concourse:
the Friend said, he hoped it would not be required of me.

This I mention to convince you that universal love prevails
in the hearts of some who are unknown to the world,
and hardly known to their own brethren; and this is not to be wondered at.
Eli did not know the inward exercise of Hannah,
and the prophet Elijah thought he had been left alone,
until the Lord told him he had seven thousand in Israel who had not bowed to Baal.
The prophet Samuel also,
when he looked out with an eye of reason on the goodness of the stature of Eliab, said,
"`Surely the Lord`'s anointed is before him;`" so now,
unless the Lord be pleased to reveal things to us, we are liable to mistake.
But blessed be the name of our most gracious God, who is the same that ever he was,
he sees not as man sees; for man looks at the outward appearance,
but God looks at the heart.

I received your second letter just as I was going out of London,
of which I have sent you a copy, with some annotations: my view therein is,
that if you think it may be of benefit to any, you may communicate it; if not,
let it lie by you.

I take great notice of your Christian love and good advice in your second letter,
and do accept of it very heartily; and can assure you,
that my labour is not to gather people into a formality,
but I labour according as the Lord enables me, to gather souls to Christ,
who is able to make the deceitful hearts of the children of men, plain, honest,
upright and clean; and when "`the inside is clean, the outside will be clean also.`"
But I freely acknowledge that the glory of the true church or mystical body,
or bride of Christ (which is made up of souls,
who have entered into covenant with the Lord, to love and serve him forever), is within;
"`her clothing is of wrought gold,`" and the curious
needlework of virgin wisdom is upon her;
for she has been stripped of all her old rags or garments of righteousness and unrighteousness.
Having been washed in pure water,
her Bridegroom has anointed her with holy oil--the holy unction of his Spirit;
and he is clothing her with the beautiful garment
of his salvation--the robe of his righteousness.
She is depending on him for her daily bread; so that she is not eating her own bread,
nor wearing her own apparel.
She cannot be content with only bearing his name,
but longs to be made more and more a partaker of his divine nature.
And the love of her Lord has been and still is so largely extended to her,
with her love so to him, that she is wholly subject to him; he rules in love,
and she obeys in love, and this makes all things easy.
She has no will of her own, but the will of her Lord is her will in all things:
all his commands are pleasant to her, because she delights to wait on him,
and to serve in his presence, and had rather be deprived of all outward enjoyments,
than of his presence, and the enjoyment of his favour.
Her conduct is adorned with humility and meekness,
her steps are comely in the eyes of her Beloved;
"`all her children are taught of the Lord, established in righteousness,
and great is their peace.`"
And my soul may say to the praise and glory of God,
that no greater comfort can be enjoyed on this side the grave,
than to be a child or member of this church.

And now, my dear friend,
I will give you a short account of the dealings of the Lord with me in my young years;
how he brought my soul through fire and water.
For what end this has lived in my mind I know not,
except it be for our spiritual communion;
but when my soul is lowest and nearest to the Lord in the simplicity of truth,
then is my heart opened and my mind filled with divine love respecting this matter.
I desire you to peruse it inwardly, when you are retired,
and not to judge of it before you have gone through it;
and then judge as freely as you please:--

I was baptized and educated in the way of the church of England;
and went to school to a minister thereof, whom I loved and honoured greatly;
he showed great kindness and tenderness to me.
In those days I looked on the ministers to be like angels,
that brought glad tidings to the children of men.
When I was about fourteen years of age, I went to live at a knight`'s house,
who kept a chaplain; I observed his conduct, and saw it was vain,
and I thought it ought not to be so, and was troubled in my mind;
for I then began to think on my latter end and also on eternity,
and I had no assurance of salvation or a state of happiness,
if it should please the Lord to send the messenger of death to call me away.

So the fear of the Lord laid hold on my mind, and I began to search the Scriptures,
and found they testified that "`the wicked should be turned into hell,
and all those that forget God.`"
And I saw that both priests and people did too generally
"`forget God,`" as soon as they came off their knees,
or from their devotion.
I was much afraid of hell, and lacked an assurance of a place in the kingdom of heaven.
Then I began to think on the great promises that were made for me in my baptism,
as they called it, whereby they said I was made a member of Christ, a child of God, etc.,
that I should renounce the devil and all his works,
the pomps and vanities of this wicked world, and all the sinful lusts of the flesh,
and should keep God`'s holy will and commandments.
I thought indeed this was the way to obtain a place in the kingdom of heaven;
but I had no power to do what I ought to do, nor to forsake what I ought to forsake,
for I was very proud, vain and airy.

But as I was thus inwardly exercised, and outwardly searching the Scriptures,
my understanding was more and more opened.
I read and took notice that the ministers of Christ, whom he qualified,
and sent forth to preach, were to do it freely; for Christ said,
"`Freely you have received,
freely give,`" and that those who run when the Lord never sent them,
"`should not profit the people at all.`"
Many such things opened in my mind, and I used to ponder them in my heart;
also the promises to the flock in the 34th of Ezekiel,
where the Lord promised to bind up that which was broken,
and strengthen that which was sick.
These and similar portions of the Scriptures were very comfortable to me,
for I was sick of my sins, and my heart was broken many times before the Lord.
I thought, "`Oh I that I had lived in the days of Christ,
I would surely have been one of those that followed
him;`" and I grieved because the Jews crucified him.
Thus I loved Christ in the outward appearance, and could have said, as Peter said,
"`far be it from you Lord to suffer:`" yet I did
not know he was so near me by his Holy Spirit.
But I was convinced that the hireling shepherds, who teach for hire and divine for money,^
footnote:[Micah 3:11]
were not the ministers of Christ, by the testimony of the prophets and of Christ himself,
who said, "`By their fruits you shall know them.`"
So I left going to hear them, and walked alone:
for I had gone till a fear followed me into the worship house,
and I thought it would be just upon me,
if I was made an example for my inattention to the Spirit of Truth.

When I was about fifteen years old,
it pleased God to send the spirit of grace and supplication into my heart,
by which I prayed fervently unto the Lord: there was a divine breathing in my soul:
I had no life in my forms of prayer, except that one which Christ taught his disciples,
for which I have always had a reverent esteem; but when I was in a state to pray,
I found that the Spirit made intercession in me and for me,
according to the present necessity of my soul.
I remember the expressions that used to run through my mind were--"`O Lord! preserve
me in your fear and in your truth,--O Lord! show me your way,
and make known your mind and will unto me;`"--and I thought I was ready to obey it,
and much desired to know the people of God; for my soul cried,
"`O Lord! where do you feed your flock;
why should I be as one that is turned aside from the flocks of your companions?`"
O, the drawing cords of your divine love!
O,
you did draw my soul with longings and breathings
after the knowledge of the only true God,
and of Jesus Christ!
There was then no condemnation for the sins of ignorance, which the Lord winked at;
but he called me to repent and forsake my pride and vain company,
which was a great cross to the will of the flesh.
Yet I took it up for several months; and while I did so,
my soul had great peace and divine comfort;
so that many times the enjoyment of divine love was more to me than my natural food,
or any outward thing.
I remember when the family used to ask me why I did not come to meals,
I used to think I had food to eat that they knew nothing of.
And in those times of retirement,
I had manifestations of sufferings that I should go through,
and a sight of several things which I met with since; and in those times I walked alone.

I was convinced that the Quakers held the principles of Truth,
and that their ministry was the true ministry: but I dwelt then far from any of them,
only thus it had happened:--When I was about twelve years old,
I was at a meeting or two of theirs, and the doctrine of one man that preached there,
proved to me, as the wise man terms it, like bread cast upon the waters,
for it was found after many days:
the sound of his voice seemed to be in my mind when I was alone,
and some of his words came fresh into my remembrance;
and the voice and the words suited with the exercise of my mind.
At that time I met also with a little book of theirs,
and finding the doctrine it contained agreed with the doctrine of the apostles,
I was confirmed in my judgment, that their profession agreed with the truth:
but I did not join with them;
for by that time flesh and blood began to be very uneasy under the yoke of retirement,
and to groan for liberty.

I was about sixteen years old; and the subtle enemy lay near,
and did not lack instruments: so I was persuaded by reasoning with flesh and blood,
that I was young, and might take a little more pleasure,
and might serve God when I was older.
I let go my exercise of watching and praying, left off retirement,
and let out my love to visible objects.
Pride and vanity grew up again; the divine, sweet, meek, loving Spirit withdrew,
and I could not find it again when I pleased, although I did seek it sometimes:
for I could have been pleased with the sweet comforts of his love,
yet I did not like to bear the daily cross.
And being convinced that was required by the Quakers`' principles,
and believing they did enjoy the sweetness of divine love in their meetings,
I went sometimes a great way to a meeting to seek for divine refreshment there;
but to no purpose; for I was like some dry stick that had no sap nor virtue,
unto which rain and sunshine,
summer and winter are all alike.--Thus it was with me for about three years.

Oh, the remembrance of that misspent time!
Oh, the tribulation that came on me for my disobedience, is never to be forgotten!
But when I was about nineteen years of age,
it pleased the Almighty to send his quickening Spirit again into my heart,
and his light shined into my mind; all my transgressions were set in order before me,
and I was made deeply sensible of my great loss.
And then, oh then! the vials of the wrath of an angry Father,
were poured out on the transgressing nature.
Oh, then I cried, "`woe is me! woe is me!
I am undone--I have slain the babe of grace--I have
crucified the Lord of life and glory to myself afresh,
although I have not put him to open shame.`"
For I had been preserved in moral honesty in all respects, to that degree,
that I dared not tell a lie, or speak an evil word, and could be trusted in any place,
and in any thing; for this would be in my mind many times,
that if I was not faithful in the unrighteous mammon
I should not be trusted with heavenly treasure.
But notwithstanding my righteousness, He whose eye penetrates all hearts,
found me so guilty, that I thought there was no mercy for me.
Oh! that testimony of our blessed Lord Jesus, I found to be true, namely,
"`Except your righteousness exceed the righteousness of the Scribes and Pharisees,
there is no admittance into the kingdom of heaven or favour of God.`"

But after many days and nights of sorrow and great anguish, having no soul to speak to,
it came into my mind to give myself up into the hands of God; and I said,
"`O Lord! if I perish, it shall be at the gate of your mercy;
for if you cast me into hell, I cannot help myself; therefore I will give up my soul,
my life, and all into your holy hand: do your pleasure by me; your judgments are just,
for I have slighted your sweet love and have slain the babe of grace.`"
And as I sunk down into death, and owned and submitted to the judgments of God,
my heart was broken, which before was hard;
and it pleased my merciful Father to cause his divine,
sweet love to spring again in my hard, dry, and barren soul, as a spring of living water;
the fire of the wrath of God was mightily abated,
and the compassionate love of a tender Saviour my soul felt.
I had living hope raised in my mind: yet greater afflictions came afterwards;
so that I may say by experience, "`Strait is the gate and narrow is the way,`" indeed,
"`that leads unto life.`"
And I have cause to believe,
none but such as are made willing to be stripped
of all that belongs to self or the old man,
and do become as little children, can rightly or truly enter in at the strait gate.
And I do find by experience, that no vulture`'s eye, no venomous beast,
nor lofty lion`'s whelp, can look into or tread in this holy,
narrow way--Oh! the longing there is in my soul, that all might consider it.
But to proceed:--

I thought all was well, and said in my heart, "`The worst is now over,
and I am again taken into the favour of God:`" so I was led into an elevation of joy,
though inwardly in silence.
But in a few days my soul was led into a wilderness where there was no way, no guide,
no light that I could see, but darkness such as might be felt indeed:
for the horrors of it were such, that when it was night I wished for morning,
and when it was morning I wished for evening.
The Lord was near, but I knew it not: he had brought my soul into the wilderness,
and there he pleaded with me by his fiery law and righteous judgments.
The day of the Lord came upon me, which burnt as an oven in my bosom,
till all pride and vanity were burnt up, my former delights were gone,
my old heavens were passed away within me, as with fire,
and I had as much exercise in my mind of anguish and sorrow as I could bear,
day and night for several months, and not a drop of divine comfort.
I could compare my heart to nothing, unless it were a coal of fire, or a hot iron;
no brokenness of heart or tenderness of spirit;
although I cried to God continually in the deep distress of my soul,
yet not one tear could issue from my eyes.

Oh! the days of sorrow and nights of anguish that I went through, no tongue can utter,
nor heart conceive which has not gone through the like.
I could have wished I had been some other creature,
that I might not have known such anguish and sorrow;
for I thought all other creatures were in their proper places.
But my troubles were aggravated by the strong oppression and temptation of Satan,
who was very unwilling to lose his subject: so he raised all his forces,
and made use of all his armour which he had in the house:
and I found him to be like a strong man armed indeed;
for he would not allow me to enter into resignation,
but would have me look into mysteries that appertain to salvation,
with an eye of carnal reason.
And because I could not so comprehend,
he caused me to question the truth of all things
that are left upon record in the Holy Scriptures,
and would have persuaded me into the Jews`' opinion concerning Christ;
and many other baits and resting places he laid before me.
But my soul hungered after the true bread, the bread of life,
which came from God out of heaven, which Christ testified of,^
footnote:[See John 6 beginning at the 27th verse, to the end.]
which I had felt near, and my soul had tasted of.
And although the devil prompted me with his temptations, my soul could not feed on them,
but cried continually, "`Your presence,
Lord! or else I die--Oh! let me feel your saving arm,
or else I perish--O Lord I give me faith.`"

Thus was my soul exercised in earnest supplications unto God night and day;
and yet I went about my outward occasions, and made my complaint to none but God only.
And I have often since considered,
that the subtle serpent finds suitable baits for the soul that
can be content to feed on anything below the enjoyment of God.
So having known the terrors of God and the subtle wiles of Satan,
I am concerned sometimes to persuade people to repent,
and to warn them to flee from the wrath to come.

Now all my faith which I had before, while in disobedience,
proved like building on a sandy foundation.
All the comfort I used to have in reading the Scriptures, was taken away;
and I dared not read for some time, because it added to my condemnation.
So I was left to depend on God alone, who caused me to feel a little hope at times,
like a glimmering of light underneath my troubles, which was some stay to my mind:
if it had not been so, I had fallen into despair.
But I much desired to be brought through my troubles the right way,
and not to shake off or get over them in my own time.
I had not freedom to make known my condition to any person; for I used to think,
if the Lord did not help me, in vain was the help of man:
and I have since seen that it was well I did not, on several accounts;
for I might have come to a loss if I had done so, as it was the will of God to humble me,
and to turn up and throw down all that which might be imputed to man or self,
that I might know the work or building of the Lord
to be raised from the foundation of his own power,
where there is none of man`'s building; that all the glory might be given to him alone.
For we are very apt to say in effect, "`I am of Paul, I am of Apollos, I am of Cephas,
and I of Christ,`" as if Christ was divided:
but the Lord will not give his glory to another, nor his praise to graven images.
For as you, my friend, well observe, the chief end that we ought to labour for,
is to make people sensible of their corruption, to direct them to the word that is near,
and to be good examples to them.

So, in the Lord`'s due and appointed time,
when he had seen my suffering of that fiery kind to be sufficient,
he was pleased to cause his divine love to flow in my bosom in an extraordinary manner;
and the Holy Spirit of divine light and life did overcome my soul.
Then a divine sense and understanding was given me
by which to know the power and also the love of God,
in sending his only Son out of his bosom into the world,
to take upon him a body of flesh,
wherein he did go through the whole process of suffering for the salvation of mankind;
and so did break through and break open the gates of death,
and repair the breach that old Adam had made between God and man,
and restored the path for souls to come to God.

And the Almighty was pleased at that time to make my simple soul sensible,
that he did send the spirit of his Son into my heart,
in order to lead me through the process of his suffering; that as he died for sin,
so I might die to sin, by bearing the daily cross, and living in self-denial, humility,
and obedience to God, my Heavenly Father, in all things he should require of me.
And then the baptism of the Holy Spirit, compared to water as well as fire,
my soul came to witness;
and the ministration of judgment and condemnation I saw had a glory in it,
which made way for the ministration of life.

The axe of God`'s word was laid to the evil root of the tree,
and the voice of him who preached repentance my soul heard,
that called for the mountains to be laid low, and the valleys to be raised, that is,
the mountains of my natural temper,
that a plain way might be made for the ransomed soul to walk in.
And the Lord showed me how John the Baptist came to be counted
the greatest prophet that was born of a woman,
because he was the forerunner of Jesus Christ, and is rightly termed the mourner;
and how the least in the kingdom of heaven,
is greater than he that is under his ministration only, which was to decrease;
but the ministration of Jesus was to increase,
whose baptism is with the Holy Spirit and with fire,
and he will thoroughly purge his floor.
Then I came to witness that it is indeed the work of God
to believe rightly and truly on Him whom God has sent;
that this purifying, saving faith is the gift of God,
and the very spring and vital principle of it, divine love.
Then I mourned over Him whom I had pierced with my unbelief and hardness of heart;
and I did eat my bread with weeping, and mingled my drink with tears.

I was between nineteen and twenty years of age when
these great conflicts were on my mind:
by them I was brought very humble; and I entered into solemn covenant with God Almighty,
that I would answer his requirings, if it were to be the laying down my natural life.
But when it was showed me that I ought to take up the cross in a little thing,
I had like to have hearkened to the reasoner again,
and been disobedient in the day of small things:
for although I had gone through so much inward exercise,
yet I was afraid of displeasing my superiors, being then a servant to great persons.
It was shown me, that I should not give flattering titles to man;
and I was threatened inwardly, that if I would not be obedient to the Lord`'s requirings,
he would take away his good Spirit from me again.
So I was in a strait; I was afraid of displeasing God, and afraid of displeasing man;
till at last I was charged by the Spirit, with honouring man more than God:
for in my address to God I did use the plain language,
but when I spoke to man or woman I must speak otherwise, or else they would be offended.

Some would argue, that God Almighty being that only One,
therefore the singular language was proper to him alone:
and man being made up of compound matter, the plural language was more proper to him, etc.
Oh! the subtle twistings of proud Lucifer that I have seen, would be too large to insert;
but although God Almighty is that only One, yet is he the Being of all beings,
for in him we live, move, and have our being.
But let the cover be what it would, I had Scripture on my side,
which they called their rule;
and I knew proud man disdained to receive that language from an inferior,
which he gave to the Almighty.
So it became a great cross to me:
but it was certainly a hinderance in the way of the progress of my soul,
until I gave up to the Lord`'s requirings in this small thing.
These things I signify to you, dear friend, in great simplicity,
that you may see how the Lord leads out of the vain customs that are in the world,
not only in what I have mentioned, but also in many other things; and into that humble,
self-denying way which Christ both taught and practised, when he was visible among men.
Christ is the true Christians`' pattern, and his Spirit their leader.

And now I show you this in truth and sincerity,
because I would not be misunderstood by you: I am a single soul,
wholly devoted to the Lord, and so do not plead for a form for form`'s sake;
neither do I plead for a people as a people; for we are grown to be a mixed multitude,
much like the children of Israel, when they were in the wilderness.
But this I may say to the praise and glory of God;
the principle that we make profession of, is the very Truth, namely,
Christ in the male and in the female, the hope of glory: and Christ, you know,
is the Way, the Truth, and the Life, and none comes to God but by him.
So there is a remnant, who, like Joshua and Caleb of old,
are true to the Lord their spiritual Leader, and follow him faithfully;
and they stand clear in their testimonies against all dead formalities,
which are but as images, when the vital principle, namely, the divine love, is withdrawn.

And yet as the spirit of Jesus leads out of all vain
customs and traditions which are in the world,
and into the plain, humble, meek,
self-denying life and conduct which Christ walked in while he was visible among men,
I could wish all to follow the leadings of his Spirit herein,
that thereby they may confess him before men.
But if it please the Almighty to accept of souls,
without leading them through such fiery trials as he brought me through,
or without requiring such things of them as he required of me,
far be it from me to judge that such have not known the Lord,
or the indwellings of his love, if the fruits of the spirit of Jesus be plain upon them:
for every tree is known by its fruits, and to our own master we must stand or fall.

But dear friend, as you well observed,
purification is a gradual work--I may say so by experience:
for when the old adversary could no longer draw me
out into vain talking and foolish jesting,
then he perplexed me with vain thoughts;
some of which were according to my natural disposition, and some of them quite contrary.
Oh!
I cried mightily unto the Lord for power over vain thoughts;
for they were a great trouble to me;
and I stood in great fear lest one day or other I should fall by the hand of the enemy.
But the Lord spoke comfortably to my soul in his own words left upon record, "`Fear not,
little flock,
it is your Father`'s good pleasure to give you the kingdom;`"
and the Lord gave me an evidence along with it,
that my soul was one of that little flock.
Another time, when I was very low in my mind, these words sprang with life and virtue:
"`Although you have lain among the pots, yet I will give you the wings of a dove,
covered with silver, and her feathers of yellow gold.`"
Oh! it was wonderfully comfortable to me when the
Holy Spirit did bring a promise to my remembrance,
and gave me an evidence that it was my portion.
So I pondered on this,
concerning "`the wings of a dove,`" and I thought it must needs be the wing of innocency,
whereby my soul might ascend unto God by prayer, meditation, and divine contemplation.

I took delight to pray in secret and fast in secret,
from the secret outgoings of my mind as well as I could,
and my Heavenly Father who sees and hears in secret, did reward me openly.
For then, when I went to meetings, I did not sit in darkness, dryness and barrenness,
as I used to do in the time of my disobedience;
but I did reap the benefit of the end of the coming of Christ, who said,
"`The thief comes not except to steal, and to kill, and to destroy:
I am come that they might have life, and that they might have it more abundantly.`"
The thief had, in the time of my disobedience, stolen my soul from Jesus, who said,
"`Whoever loves father or mother, etc., or his own life more than me,
is not worthy of me.`"
So it had been with me, and I missed the benefit of reaping the end of his coming,
for several years; but he in mercy being returned,
afforded my bowed-down soul the enjoyment of his divine presence,
and was pleased to cause his love, which is the true life of the soul,
so to abound in my bosom in meetings, that my cup did overflow.
And I was constrained, under a sense of duty, to kneel down in the congregation,
and confess to the goodness of God, also to pray to him for the continuation of it,
and for power whereby I might be enabled to walk worthy of so great a favour,
benefit and mercy, that I had received at his bountiful hand.

And I remember after I had made public confession to the goodness of God,
my soul was as if it had been in another world:
it was so enlightened and enlivened by the divine love,
that I was in love with the whole creation of God,
and I saw everything to be good in its place.
I was showed things ought to be kept in their proper places,
that the swine ought not to come into the garden,
and the clean beasts ought not to be taken into the bedchamber;
that as it was in the outward, so it ought to be in the inward and new creation.
So everything began to preach to me; the very fragrant herbs, and beautiful,
innocent flowers had a speaking voice in them to my soul,
and things seemed to have another relish with them than before.
The judgments of God were sweet to my soul, and I was made to call to others sometimes,
to come taste and see how good the Lord is, and to exhort them to prove the Lord,
by an obedient, humble, innocent walking before him,
and then they would see that he would pour out of
his spiritual blessings in so plentiful a manner,
that there would not be room enough to contain them;
but the overflowings would return to him who is the Fountain, with thanksgivings, etc.
And I was made to warn people, that they should not provoke the Lord by disobedience:
for although he bears and suffers long,
as he did with the rebellious Israelites in the wilderness,
yet such shall know him to be a God of justice and judgment,
and shall be made so to confess one day.

Thus, dear friend, I have given you a plain,
but true account of my qualification and call to the service of the ministry.
But it was several years before I came to a freed state, or even temper of mind:
for sometimes clouds would arise and interpose between my soul and the rising Sun,
and I was brought down into the furnace often,
and found by experience that every time my soul was
brought down as into the furnace of affliction,
that it did still come up more clean and bright;
and although the cloud did interpose between me and the rising Sun,
yet when the Sun of Righteousness did appear again,
he brought healing as under his wings, and was nearer than before.

Thus dear friend, I express things in simplicity,
as they were represented to me in the manifestation of them in the morning of my days.
I came to love to dwell with judgment, and used often to pray, saying,
"`O Lord! search me and try me, for you know my heart better than I know it;
and I pray you let no deceitfulness of unrighteousness lodge therein;
but let your judgments pass upon everything that is contrary to your pure,
divine nature.`"
Thus my soul used to breathe to the Lord continually,
and hunger and thirst after a more full enjoyment of his presence.
Although he is a consuming fire to the corrupt nature of the old man,
yet my soul loved to dwell with him.
I found many sorts of corruptions would be endeavouring to spring up again;
but I resigned up my mind to the Lord,
with desires that he would feed me with food convenient for me.
And this I can say by experience,
that the soul that is born of God does breathe to him as constantly by prayer,
as the sucking child, when it is born into the world,
does draw in and breathe out the common air;
even so the child of God does draw in and breathe forth the breath of life,
by which man was made a living soul to God.
And this breathing that is pure and divine, all that are in the old man or fallen nature,
know nothing of; it is a mystery to them; but the babe in Christ knows it to be true.

And although the children in our Father`'s family are of several ages,
growths or statures, both in strength and understanding,
yet this I have observed in all my travels, that those who live to God,
continue in a state of breathing to him while here,
and hunger and thirst after a more full enjoyment of his divine presence;
that as every day brings us nearer to the grave,
so every day the soul may be brought into a more divine union and communion with God.
It is a certain sign to me, of the divine life and health of a soul,
if I find it sweetly breathing unto the Lord,
and hungering and thirsting after his righteousness.
And it is very evidently seen, and easily known by the conduct of persons,
what manner of spirit does govern in them;
although many will not believe these things if declared to them;
neither will they try whether it be so or not,
but they are satisfied with the husk of religion.
Oh! what will they do when the rudiments and beggarly elements of this world fall off,
and all our works must pass through the fire: my very soul mourns for them;
but we must press forwards and leave them,
if they will not arise out of their false rest.

Dear friend, as you well observe,
it is a great help to the soul to know its own corruptions, and from where it is fallen,
that it may know where to return.
These things are very true: the knowledge of them has been a great comfort to me,
and so have the experiences of the servants of the Lord,
agreeably to the testimonies left on record,
which are as waymarks to the spiritual traveller;
and we have a great privilege in and by them:
but above all in and by Christ our holy Pattern and heavenly Leader, who has said,
"`My judgment is just, because I seek not my own will,
but the will of the Father which has sent me.`"
My soul prizes the knowledge of his footsteps, the leading of his Spirit,
the Spirit of Truth, the Comforter, whom the Father has sent, to lead us into all truth.
And O says my soul,
that we may follow the leadings of our unerring Guide
in all things that he may lead us into!
I have good cause to believe he will bring us through
all tribulations to the honour of God and our comfort:
for the Lord has brought my soul through many trials, one after another,
as he saw fitting, some more of which I may give a hint of.

After my inward tribulation was abated, then outward trials began;
for there were some of no small account,
that endeavoured with all their might and cunning,
to hinder the work from prospering in me: and as Saul hunted David,
and sought to take away his natural life, so these hunted my soul to take away its life,
which it had in God: but all wrought together for my good.
I have often seen, and therefore may say, the Lord knows what is best for his children,
better than we know for ourselves: and so my enemies,
instead of driving my soul away from God, drove it nearer to him.
This trial caused me to prove the spirit which had the exercise of my mind,
and I found it to be the Spirit of Truth,
which the worldly and self-minded cannot receive;
for I found the nature of it to be harmless and holy, and to lead me to love my enemies,
to pity them and pray for them.

This love was my preservation;
and as I gave up in obedience to the operation and requiring of this meek Spirit,
it ministered such peace to my soul, as the world cannot give.
But there was a disposition in me to please all,
which I found very hard for me to be weaned from, so as to stand single to God:
for when I did fear man, I had nothing but anguish and sorrow;
and I used often to walk alone and pour out my complaint to the Lord.
But after a long time, when the Lord had tried my fidelity to him as he saw fitting,
one day as I was sitting in a meeting in silence, waiting upon the Lord,
to know my strength renewed in him, this portion of Scripture was given to me:
"`Comfort my people, says your God: speak comfortably to Jerusalem, and cry unto her,
that her warfare is accomplished, that her iniquity is pardoned;
for she has received of the Lord`'s hand double for all her sins.`"
This brought great comfort to my soul; I treasured it in my heart,
and made this observation, that from that time the Lord gave my soul,
as the apostle Peter expresses it,
a more abundant entrance into the heavenly kingdom or New Jerusalem,
whose walls are salvation and her gates praise; my mind was brought into more stillness,
and troublesome thoughts were in a good degree expelled;
my outward enemies grew weary of their work and failed of their hope.
The praise I freely, in great humility, offer up and ascribe to Almighty God;
for it was his own work to preserve me from many strong temptations.

So after I had been favoured with peace at home every way,
I was drawn by the Spirit of love, to travel into the north of England.
On my journey my soul had many combats with the evil spirit:
when I was asleep he tormented me as long as he could.
I have, indeed, had a long war with the devil many ways;
abundance of courage was given me to make war with him;
and I always gained the victory when cowardly, fearful nature was asleep,
which was comfortable to my mind:
and I did hope that the Lord would give me perfect
victory over the devil when I was awake,
as he had let me see it to be so when I was asleep.
The Spirit which led me forth, was to me like a needle of a compass,
touched with a loadstone; for so it pointed where I ought to go,
and when I came to the far end of the journey.
In those days I had certain manifestations of many things in dreams,
which did come to pass according to their significations;
I was many times forewarned of enemies, and so was better able to guard against them.
I travelled in great fear and humility,
and the Lord was with me to his glory and my comfort, and brought me home again in peace.

In the year 1697, in the sixth month, as I was sitting in the meeting in Gloucester,
which was then the place of my abode,
my mind was gathered into perfect stillness for some time,
and my spirit was as if it had been carried away into America; and after it returned,
my heart was as if it had been dissolved with the love of God,
which flowed over the great ocean,
and I was constrained to kneel down and pray for the seed of God in America.
The concern never went out of my mind day nor night,
until I went to travel there in the love of God,
which is so universal that it reaches over sea and land.
But when I looked at my concern with an eye of human reason,
it seemed to be very strange and hard to me; for I knew not the country,
nor any that dwelt therein.
I reasoned much concerning my own unfitness, and when I let in such reasonings,
I had nothing but death and darkness; and trouble attended my mind:
but when I resigned up my all to the Lord, and gave up in my mind to go,
then the divine love sprang up in my heart,
and my soul was at liberty to worship the Lord as in the land of the living.

Thus I tried and proved the concern in my own heart,
till at last these words ran through my mind with authority,--"`The
fearful and unbelieving shall have their portion with the hypocrite,
in the lake that burns with fire and brimstone; which is the second death.`"
This brought a dread; I then told my husband that I had a concern to go to America;
and asked him if he could give me up.
He said he hoped it would not be required of me; but I told him it was;
and that I should not go without his free consent,
which seemed a little hard to him at first.
A little while after, I was taken with a violent fever, which brought me so weak,
that all who saw me thought I should not recover.
But I thought my day`'s work was not done,
and my chief concern in my sickness was about going to America.
Some were troubled that I had made it public, because they thought I should die,
and people would speak reproachfully of me; and said, if I did recover,
the ship would be ready to sail before I should be fit to go, etc.
But I thought if they would only carry me and lay me down in the ship, I should be well:
for the Lord was very gracious to my soul in the time of my sickness,
and gave me a promise that his presence should go with me.
And then my husband was made very willing to give me up; he said,
if it were for seven years, rather than to have me taken from him forever.

So at last all those difficulties passed over,
and I sailed from Bristol in the ninth month, 1697, with my companion Mary Rogers.
The dangers we were in at sea, and the faith and courage the Lord gave to my soul,
would be too large here to relate;
for I had such an evidence of my being in my proper place,
that the fear of death was taken away.
Oh! it is good to trust in the Lord and be obedient to him,
for his mercies endure forever.

About the middle of the twelfth month, 1697, through the good providence of the Almighty,
we arrived in Virginia.
As I travelled along the country from one meeting to another,
I observed great numbers of black people that were in slavery.
They were a strange people to me;
I wanted to know whether the visitation of God was to their souls or not;
and I observed their conduct, to see if I could discern any good in them.
After I had travelled about four weeks,
as I was in bed one morning in a house in Maryland,
after the sun was up I fell into a slumber,
and dreamed I was a servant in a great man`'s house,
and that I was drawing water at a well to wash the uppermost rooms of the house.
When I was at the well, a voice came to me,
which bid me go and call other servants to help me, and I went presently.
But as I was going along in a very pleasant green meadow, a great light shined about me,
which exceeded the light of the sun, and I walked in the midst.

As I went on in the way, I saw a chariot drawn with horses coming to meet me,
and I was in care lest the light that shone about me should frighten the horses,
and cause them to throw down the people whom I saw in the chariot.
When I came to them, I looked on them,
and I knew they were the servants I was sent to call:
I saw they were both white and black people, and I said unto them,
"`Why have you stayed so long?`"
They said, "`The buckets were frozen,
we could come no sooner:`"--So I was satisfied the call
of the Lord was unto the black people as well as the white;
and I saw the fulfilling of it in part, before I returned out of America,
with many more remarkable things, which would be too tedious here to mention.

But O how great is the condescension and goodness of God,
to poor mankind! it is a good observation on the tender dealings of our Heavenly Father,
to set up our Ebenezer, and say,
"`Hitherto has the Lord helped us:`"--and indeed I may say to his praise,
it has been so with me through many straits and difficulties, more than I can number;
and they have all wrought together for the good of my soul.
And I have cause to believe, that every son or daughter whom he receives, he chastens,
tries, and proves; and those who do not bear the chastisements of God,
do prove bastards and not sons.
But I may say, as one did of old, "`It is good for me that I have been afflicted,`" etc.,
and that it is good to follow the leadings of the Spirit of God, as faithful Abraham did,
who was called the friend of God,
and who did not withhold his only son when the Lord called for him.
And it is my belief the Lord will try his chosen ones as gold is tried,
and will yet refine them as gold is refined.
And what if he brings us yet down again into the furnace, which way it shall please him,
until we are seven times refined;
we shall be the better able to bear the impression of his image upon us in all our conduct.
And if the day should come, wherein none shall buy nor sell,
that have not the mark of the beast, either in their right hands or in their foreheads,
it is but what has been told us beforehand: and those that will know an overcoming,
it must be by the blood of the Lamb, (that is,
by abiding in the meek love and suffering seed), and by the word of their testimony;
not loving their lives unto death.
We may observe that those who had not the mark of the beast in their foreheads,
if they had it in their right hands it would do;
they could show it if there was occasion, to take off a stroke.

O the mystery of iniquity, how secretly it works!
We may well say, the testimony that Jesus bore to the Scribe who desired to follow him,
is very true--"`Foxes have holes, and the fowls of the air have nests,
but the Son of man has not where to lay his head.`"
O innocent Truth!
O plain, meek, humble Jesus!
Where does he repose?
Where does he reign without molestation?

Dear friend, excuse my freedom with you, for the love of God constrains me:
and I do believe the Lord will show you yet further
what testimony you must bear for his name,
and what you must suffer for his sake, if faithful.
For trying times will come, and offences will be given and taken;
but there is nothing will offend those that love the Lord Jesus above all.
Many murmured and were offended at Jesus when he told them the truth,
and that which was of absolute necessity for all to know and witness in themselves;
as we read in the 6th of John, beginning at the 32nd verse.
By that time he had done, many of his disciples went from him:
then said he to the twelve, "`Will you also go away?`"
but Peter said, "`Lord, to whom shall we go?
You have the words of eternal life.
And we believe and are sure that you are that Christ, the Son of the living God.`"
So God has given the faithful to believe, yes,
and we are sure that the Spirit of Truth is come,
that leads the followers of it into all truth;
and that Christ who is one with his Spirit,
and who was once offered to bear the sins of many,
has appeared again the second time without sin unto salvation.

Oh! surely the goodness of God has been very great
to the children of men from age to age,
and from one generation to another, ever since the fall of our first parents.
The more my mind penetrates into it,
the more I am likely to be swallowed up in admiration of
his condescension and goodness through all his dispensations,
but above all in the manifestation of Jesus Christ, our holy Pattern and heavenly Leader.
O my soul! praise him for the knowledge of his holy footsteps,
whom God gave for a light to us Gentiles,
and to be his salvation unto the ends of the earth;
and has given his Spirit to dwell in us, and accepted our souls to dwell in him.
O admirable goodness!
Shall we leave him?
He is the Word of eternal life, and where shall we go?
So far as any are followers of Jesus,
so far I desire to follow them or to be one with them, and no farther.
Let these do what they will, if any will go back into the sea,
out of which the beast arises, and receive his mark, our Leader is not to be blamed;
He holds on his way, and causes his trumpet to be blown in Zion,
and an alarm to be beaten in his holy mountain:
and whoever hears the sound of the trumpet, and does not take warning,
if the sword of the Lord do come, in any kind, and take him away,
his blood shall be upon his own head;
he heard the sound of the trumpet and took not warning:
but he that takes warning shall deliver his own soul.
Great is the duty of the watchman,
and great is the kindness of God as expressed in the 33rd chapter of Ezekiel.

O my dear friend! my heart is full of the goodness of the Lord.
But I must stop writing, lest I should be too tedious to you; and indeed,
it might be accounted foolishness for me to write after this manner,
to one in your station.
But I find a constraint thereto, and must commit it to your judgment, be it what it may:
and this I will assure you, my heart is plain; I mean as I speak,
and I find it safest so to do,
and to keep in humble obedience to the Lord in whatever he requires of me.
Yet I know the wisdom of God appears to be foolishness
in the eyes of the wise men of this world,
and we know that the wisdom of this world is foolishness with God,
and will prove so in the latter end to those poor souls that so mightily esteem it.
But the souls of the righteous are in the hand of the Lord,
and then shall no torment touch them; although in the sight of the unwise,
both their life and their death are taken for misery--nevertheless, they are in peace.

If you find anything on your mind, please to let me have it.
So in the love that is pure, does my soul greet you,
and remain your friend in true sincerity,

Elizabeth Webb.

The Answer to the Foregoing Letter

Dear Friend,--

I am heartily glad you are come to town again,
so that I might have an opportunity of seeing you before you leave England.
Your letter has been read with great satisfaction by myself and many of my friends;
but I have not been able to recover it yet, out of their hands.
Some have even desired to transcribe it for their edification,
and this is the reason I did not send you presently an answer;
though it has been all along upon my mind to express
the satisfaction I had at the reading thereof,
and to assure you how welcome it is to me to meet with a fellow-pilgrim
traveling to the city adorned with twelve pearls,
which is to receive all such who have made up the family of God in this wicked generation,
and have been presented for his peculiar people in all parts and denominations of Christendom.

&hellip;I had a mind to have given you at large my thoughts upon your letter.
True love is of a universal and overflowing nature, and not easily shut up by names,
notions, peculiar modes, forms, and hedges of men;
and if you will be pleased to correspond with me, even after you return from America,
I shall always be ready to answer your kindness,
and to make up again wherein I have been lacking at present;
and so recommend you to the infinite favour and protection of the Lord;
I remain in sincerity,

Your friend and servant,

Anthony William Boehm.

Strand, Jan.
2, 1712.
