[quote.epigraph, , Romans 5:3-5]
____
Tribulation worketh patience; and patience, experience; and experience, hope:
and hope maketh not ashamed;
because the love of God is shed abroad in our hearts by
the Holy Ghost which is given unto us.
____

== Introduction

The inducements to the publication of the following letter
at this distant period from the time it was written,
are--the hope entertained by some devout persons,
who have been edified by the spiritual experiences it contains,
that it may prove instructing and comforting to others alike piously disposed--and
the desire to prevent the further circulation of incorrect copies in manuscript,
such having been handed about.
It has therefore been revised,
and is now recommended to the serious perusal of all those, who,
having entered on a religious life,
may desire to find instruction and encouragement
to press forward with stability and humble resignation,
through the various probations and conflicts attending them in their Christian progress,
that they may obtain under their spiritual leader, the grace of God,
"`the end of their faith, even the salvation of their souls.`"

It may also be satisfactory to the readers, to have some account of the writer,
and of the person to whom the letter was written.
They are therefore briefly informed,
that Elizabeth Webb was an acknowledged minister among the people called Quakers, who,
from an apprehension of religious duty and the constraints of gospel love,
went from Pennsylvania to Great Britain, to visit her Friends there, about the year 1712.
When in London she contracted some acquaintance with Anthony William Boehm,
who was chaplain to Prince George of Denmark, the consort of Anne, Queen of England,
and by birth a German, yet well acquainted with the English language:
he died in the year 1722.
The divers writings on religious subjects which he has left,
show him to have been a man of a truly pious and catholic disposition;
which is also confirmed by the testimonials given
of him by men of character in his time,^
footnote:[In addition to the productions of his own pen,
A+++.+++ W. Boehm translated from German a valuable work, entitled True Christianity,
written by John Arndt.
Among those who bore testimony to his worth, as a religious character,
was the pious Isaac Watts, who said of him,
that he feared there were few such men in England, British or German,
Episcopal or Nonconformist.]
who, from their personal knowledge, mention him with great respect for his piety to God,
and benevolence to mankind.

Philadelphia, Eleventh month, 1781.
