[quote.epigraph, , Romans 5:3-5]
____
Tribulation works patience; and patience, experience; and experience, hope:
and hope makes not ashamed;
because the love of God is shed abroad in our hearts by
the Holy Spirit which is given unto us.
____

== Letter from Elizabeth Webb

[.salutation]
Worthy friend,^
footnote:[The recipient of this letter was Anthony William Boehm,
chaplain to Prince George of Denmark.
It appears Elizabeth Webb became acquainted with
Boehm during a ministerial visit to London,
about the year 1712.]

Though I am almost a stranger to you,
the kind respect you showed me when in London has laid me under an obligation,
wherein I find my mind drawn to write to you in the openings of divine love.
What I have to write has been on my mind these several weeks, in that pure,
innocent love in which the true communion of saints is known.
I have no learned method in which to deliver my religious experience,
either by word or writing, but plainly and simply as the Spirit of Truth directs.
And being the weaker vessel too, I have the greater need to beg to be excused.
I shall not write from notions and speculations
(for I look on such things as being unsafe,
and I know they are also many times unsound),
but I shall write a small part of what I have gone through,
and what my soul has tasted of the good Word of life, which is near.

Truly,
my only desire is that we may have fellowship together in God the Father of our spirits,
and in His Son, Jesus Christ our Lord,
whom my soul has known both in mercy and in judgment,
to the mortifying (in a good degree) of the fallen and corrupt nature,
and to the purifying of my heart in such a way (as I can say
to His praise) that I do not see Him through particular forms,
sects, parties, or any such thing.
No, my dear friend, I never sought after the Lord in these ways,
nor for any of these ends.
Rather, I sought after Him in my young years for salvation,
and I seek Him still for the perfect restoration of my soul in Him.
I have nothing of my own to boast of, unless it be weakness and infirmities.
Instead, I rejoice in the cross of Christ,
by which I am crucified to the world in a good degree,
and the world to me--so that I can say, "`I die daily.`"

With regard to the fondness for education, religious profession, and conversation,
these things have cast no mist before my eyes.
I can see, acknowledge,
and love the image of my Lord and Savior in any sort of profession,
if the soul has been educated in the heavenly university or school of Christ.
Nevertheless, we cannot see God in, nor find fellowship with,
all manner of life and conduct; for the way of the wicked is as if there were no God;
"`God is not in all their thoughts.`"
And as for those who despise the image of the meek, humble Jesus,
and will follow none of His precepts, nor His self-denying example while they are here,
the Lord will hereafter despise their image.
For indeed,
they shall have an image according to the seed
or spirit in which they lay down their body.
Every seed shall have its own body in the resurrection of the just and the unjust,
and every one shall receive his own sentence.

Now, my dear friend,
I will give you a short account of the dealings of the Lord with me in my younger years;
how He brought my soul through fire and water.
For what end this has now come to my mind I know not,
except it be for our spiritual communion;
but when my soul is lowest and nearest to the Lord in the simplicity of truth,
then my heart is opened and my mind filled with divine love respecting this matter.
I desire you to peruse it inwardly when you are retired,
and not judge it before you have gone through it;
and then you may judge as freely as you please.

I was baptized and educated in the way of the Church of England,
and was schooled by one of their ministers,
a man who showed great kindness and tenderness to me,
and who I loved and honored greatly.
In those days I looked upon ministers to be like angels
who brought glad tidings to the children of men.
When I was about fourteen years of age, I went to live at a knight's house,
who kept a chaplain.
I observed this chaplain's conduct and saw that it was vain,
and I thought it ought not to be so, and so I was troubled in my mind.
For in those days I began to think on my latter end, and also on eternity,
and I found I had no assurance of salvation or a state of happiness,
if it should please the Lord to send the messenger of death to call me away.
So the fear of the Lord laid hold on my mind, and I began to search the Scriptures,
and found they testified that "`the wicked should be turned into hell,
along with all those that forget God.`"
I saw that both priests and people did too generally
"`forget God,`" as soon as they came off their knees,
or from their devotion.
So I was much afraid of hell,
and lacked an assurance of a place in the kingdom of heaven.

I then began to consider the great promises that were made for me at my
baptism (as they called it) whereby they said I was made a member of Christ,
and a child of God.
In that ceremony it was said that I should renounce the devil and all his works,
the pomp and vanities of this wicked world, and all the sinful lusts of the flesh,
and should keep God's holy will and commandments.
I thought this was indeed the way to obtain a place in the kingdom of heaven;
but I found I had no power to do what I ought to do,
nor to forsake what I ought to forsake, for I was very proud, vain, and airy.
But as I was inwardly exercised in this way,
and also outwardly continued to search the Scriptures,
my understanding was more and more opened.
I read and took notice that the ministers whom Christ
qualified and sent forth to preach were to do it freely;
for Christ said, "`Freely you have received, freely give.`"
I also found that those who ran when the Lord never sent them,
"`should not profit the people at all,`" but that the Lord had
promised shepherds that would bind up what was broken,
and strengthen that which was sick (Ezek. 34).

Many such things opened in my mind, and I used to ponder them in my heart.
These and similar portions of the Scriptures became very comfortable to me,
for I was sick of my sins, and my heart was broken many times before the Lord.
I thought, "`Oh, that I had lived in the days of Christ,
I would surely have been one of those that followed Him,`"
and I was grieved because the Jews had crucified Him.
Thus I loved Christ in His outward appearance, and could have said with Peter,
"`Far be it from You Lord to suffer!`"
Yet I did not then know He was so near me by His Holy Spirit.

Then I became convinced that the hireling shepherds,
who teach for hire and divine for money, were not the true ministers of Christ.
Indeed this was made manifest to me by the
testimony of the prophets and of Christ Himself,
who said, "`By their fruits you shall know them.`"
For I had continued to hear them until a fear followed me into their worship house,
and I thought it would be just for the Lord to make an
example of me for my inattention to the Spirit of truth.
So at last I left going to hear them, and walked alone.

When I was about fifteen years old,
it pleased God to send the Spirit of grace and supplication into my heart,
by which I prayed fervently unto the Lord.
Indeed there arose a divine breathing in my soul,
but I could find no life in any forms of prayer,
except the one which Christ taught His disciples (for which I have
always had a reverent esteem). But when I was in a state to pray,
I found that the Spirit made intercession in me and for me,
according to the present need of my soul.
I remember the expressions that used to run through my mind, "`O Lord,
preserve me in Your fear and in Your truth!
O Lord, show me Your way, and make known Your mind and will unto me!`"
I thought I was then ready to obey Him, and I much desired to know the people of God;
for my soul cried, "`O Lord, where do You feed Your flock;
why should I be as one that is turned aside from the flocks of Your companions?`"

O, the drawing cords of Your divine love!
O,
You did draw my soul with longings and breathings after
the knowledge of the only true God and of Jesus Christ!
There was then no condemnation for the sins of ignorance, which the Lord winked at,
but He called me to repent and to forsake my pride and vain company,
which was a great cross to the will of the flesh.
Yet I took up this cross for several months, and while I did so,
my soul had great peace and divine comfort,
so that many times the enjoyment of divine love was more to me than my natural food,
or any outward thing.
I remember when the family used to ask me why I did not come to meals,
I thought to myself, "`I have food to eat that they know nothing of.`"
And in my times of retirement,
I had manifestations of sufferings that I should go through,
and a sight of several things which I have met with since;
but in those times I walked alone.

I was early convinced that the Quakers held the principles of Truth,
and that their ministry was the true ministry, but I then dwelt far from any of them.
But once it happened, when I was about twelve years old,
that I was at a meeting or two of theirs,
and the doctrine of a man who preached proved to be (as the wise man terms
it) "`like bread cast upon the waters,`" for it was found after many days.
Indeed, his voice seemed to sound in my mind when I was alone,
and some of his words came fresh into my remembrance,
which very much suited the exercise of my mind.
At that time I met also with a little book of theirs,
and finding that the doctrine it contained agreed with the doctrine of the apostles,
I was confirmed in my judgment that they professed the Truth.
But I did not then join with them;
for by that time my flesh and blood began to be
very uneasy under the yoke of inward retirement,
and it groaned for liberty.

When I was about sixteen years old, I found that the subtle enemy lay near,
and he did not lack instruments.
I was persuaded by reasoning with flesh and blood that since I was still young,
I could seek a little more pleasure, and then serve God when I was older.
So I let go my exercise of watching and praying, left off my daily retirement,
and let out my love to many visible objects.
Pride and vanity grew up in me again, and the divine, sweet, meek,
loving Spirit withdrew, and though I searched for it at times,
I could not find it again when I pleased.
Yes, I then would have been pleased with the sweet comforts of His love,
but I did not like to bear His daily cross.
And so having been convinced of the Quakers' principles,
and believing that they enjoyed the sweetness of divine love in their meetings,
I sometimes went a great distance to seek divine refreshment with them.
But this proved to be to no purpose;
for I was like a dry stick that had no sap or virtue, unto which the rain and sunshine,
summer and winter are all alike.
So it was with me for about three years.
Oh, the remembrance of that misspent time!
Oh, the tribulation that came on me for my disobedience is never to be forgotten!

But when I was about nineteen years of age,
it pleased the Almighty to send His quickening Spirit again into my heart,
and His light shined into my mind.
All my transgressions were set in order before me,
and I was made deeply sensible of my great loss.
And then, oh then,
the vials of wrath of an angry Father were
poured out upon the transgressing nature in me!
Oh, then I cried, "`Woe is me!
Woe is me!
I am undone; I have slain the Babe of grace!
I have crucified afresh to myself the Lord of life and glory!`"
For though in all this time I had been preserved in moral honesty in all respects,
to the degree that I dared not tell a lie, or speak an evil word,
and could be trusted in any place, and in any thing,
yet notwithstanding my outward righteousness, He whose eye penetrates all hearts,
found me so guilty that I thought there was no mercy for me.
Indeed, I found the testimony of our blessed Lord Jesus to be true, namely:
Except your righteousness exceed the righteousness of the Scribes and Pharisees,
there is no admittance into the kingdom of heaven or into favor of God.

Then, after many days and nights of sorrow and great anguish,
it came into my mind (having not spoken to a
soul) to give myself up into the hands of God.
I said, "`O Lord, if I perish, it shall be at the gate of Your mercy!
For if You cast me into hell, I cannot help myself; therefore I will give up my soul,
my life, and all into Your holy hand.
Do Your pleasure with me, for Your judgments are just,
and I have disregarded Your sweet love and have slain the Babe of grace.`"
And as I sunk down into death, and owned and submitted to the judgments of God,
my heart (which had been hard) was broken,
and it pleased my merciful Father to cause His divine,
sweet love to spring again in my hard, dry, and barren soul, as a spring of living water.
Then the fire of the wrath of God was mightily abated,
and my soul felt the compassionate bowels of a tender Savior,
and a living hope arose in my mind.

Nevertheless, greater afflictions came afterwards, so that I learned by experience,
"`Narrow is the gate and difficult is the way that leads unto life.`"
And I have cause to believe that none but those who are made willing
to be stripped of all that belongs to self or the old man,
and become as little children, can rightly or truly enter in at the narrow gate.
Indeed, I find by experience, that no vulture's eye, no venomous beast,
nor lofty lion's whelp, can look into or tread upon this holy, narrow way.
Oh, the longing there is in my soul that all might consider it!

 But to proceed: I thought all was well, and I said in my heart, "`The worst is now over,
and I have come again into the favor of God.`"
So my joy increased, though I remained inwardly in silence.
But in a few days my soul was led into a wilderness where there was no way, no guide,
and no light that I could see, but rather a darkness such as might be felt.
Indeed, the horrors of it were such that when it was night I wished for morning,
and when it was morning I wished for evening.
The Lord was near, but I knew it not.
He had brought my soul into the wilderness,
and there He pleaded with me by His fiery law and righteous judgments.
The Day of the Lord came upon me, which burned as an oven in my bosom,
till all pride and vanity were burned up.
My former delights were gone; my old heavens passed away within me (as with fire),
and I had as much exercise in my mind of anguish and sorrow as I could bear,
day and night for several months, and not a drop of divine comfort.
My heart was like a coal of fire, or a hot iron,
feeling no brokenness of heart or tenderness of spirit.
And though I cried to God continually in the deep distress of my soul,
yet not one tear could issue from my eyes.
Oh the days of sorrow and nights of anguish that I went through; no tongue can utter,
nor any heart conceive that has not gone through the like!
I could have wished I were some other creature,
so that I might not know such anguish and sorrow;
for I thought all other creatures were content in their proper places.

My troubles were aggravated by the strong oppression and temptation of Satan,
who was very unwilling to lose one of his subjects.
He raised all his forces, and made use of all the weapons which he had in the house.
Indeed, I found him to be like a strong man armed,
for he would not allow me to enter into a state of resignation,
but led me to look into mysteries that pertain
to salvation with the eye of carnal reason.
And because I could not comprehend with that eye,
he caused me to question the truth of all things
that are left upon record in the Holy Scriptures,
and would have even persuaded me to believe the Jews' opinion concerning Christ.
Many other baits and false resting places were laid before me,
but my soul hungered after the true bread, the bread of life,
which came from God out of heaven (of which Christ testified,
John 6) which I had felt near, and my soul had tasted.
And although the devil prompted me with his temptations,
my soul could not feed upon them, but cried continually, "`Your presence, Lord,
or else I die!
Oh, let me feel Your saving arm, or else I perish!
O Lord, give me faith!`"
Thus was my soul exercised in earnest supplications unto God night and day;
and yet I went about my outward responsibilities,
and made my complaint to none but God alone.

I have often since considered how the subtle serpent finds suitable baits for souls,
especially for those who are content to feed
upon something less than the enjoyment of God.
And having known the terrors of God and the subtle wiles of Satan,
I am sometimes concerned now to persuade people to repent,
and to warn them to flee from the wrath to come.

Now all my faith which I had known before (while still in disobedience),
proved to be like a house on a sandy foundation.
And all the comfort I formerly had in reading the Scriptures was taken away,
and I dared not read for some time, because it added to my condemnation.
I was left to depend upon God alone, who caused me to feel a little hope at times,
like a glimmering of light underneath my troubles.
This was like a stay to my mind, and if it had not been so,
I most certainly would have fallen into despair.

I much desired to be brought through my troubles the right way,
and not to shake off or get over them in my own time.
So I did not find freedom to make my condition known to any person,
for I thought to myself, "`If the Lord does not help me, vain is the help of man.`"
And I have since seen that it was well I did not (on several accounts),
and that I might have come to a loss if I had done so.
For I know now that it was the will of God to humble me,
and to expose and throw down all help which might be imputed to man or self,
that I might know the true work of the Lord raised from the foundation of His own power,
where there is nothing of man's building, and all the glory is given to Him alone.
For we are very apt to say, in effect, "`I am of Paul, I am of Apollos, I am of Cephas,
and I of Christ,`" as if Christ were divided;
but the Lord will not give His glory to another, nor His praise to graven images.
For as you, my friend, have well observed,
the chief end for which we ought to labor is to make people sensible of their corruption,
and to direct them to the Word that is near, and be good examples to them.

So, in the Lord's due and appointed time,
when He had seen my suffering of that fiery kind to be sufficient,
He was pleased to cause His divine love to flow in my bosom in an extraordinary manner,
and the Holy Spirit of divine light and life did overcome my soul.
Then a divine sense and understanding was given to me by which to know the power
and love of God in sending His only Son out of His bosom into the world,
and taking upon Himself a body of flesh,
and going through the whole process of suffering for the salvation of mankind.
I saw how He did break through, and break open, the gates of death,
and repair the breach that old Adam had made between God and man,
and restore the path for souls to come to God.
And my simple soul was made to understand how the Almighty did send the Spirit of
His Son into my heart in order to lead me through the process of His suffering,
so that as He died for sin, so I might die to sin, by bearing the daily cross,
and living in self-denial, humility, and obedience to God, my Heavenly Father,
in all things He should require of me.

Then my soul came to witness the baptism of the Holy
Spirit (which is compared to both water and fire);
and I saw that the ministration of judgment and condemnation
had a glory in it which made way for the ministration of life.
The axe of God's living Word was laid to the evil root of the tree,
and my soul heard the voice of Him who preached repentance and called for
the mountains to be laid low and the valleys to be raised (that is,
the mountains of my natural temper),
that a plain way might be made for the ransomed soul to walk.
And the Lord showed me how John the Baptist came to be
considered the greatest prophet that was born of a woman,
for he was the forerunner of Jesus Christ, and indeed,
the least in the kingdom of heaven is greater
than he that is under John's ministration only.
For John's ministration was to decrease, but the ministration of Jesus was to increase,
whose baptism is with the Holy Spirit and with fire,
and He will thoroughly purge His threshing floor.

Then I came to witness that it is indeed the work of God to
believe rightly and truly on Him whom God has sent,
and that this purifying, saving faith is the gift of God,
and the very spring and vital principle of it is divine love.
Then I mourned over Him whom I had pierced with my unbelief and hardness of heart;
and I did eat my bread with weeping, and mingled my drink with tears.
I was between nineteen and twenty years of age when these great conflicts were upon me,
and by them I was brought very humble.

I then entered into a solemn covenant with God Almighty,
promising I would answer His requirings even if
it were to the laying down my natural life.
But when it was shown me that I ought to take up the cross in little things,
I was quick to listen to the reasoner again,
and become disobedient in the day of small things.
For although I had gone through so much inward exercise,
still I was afraid of displeasing my superiors,
being then a servant to persons of repute in the world.
It was shown to me that I should not give flattering titles to man;
and I greatly feared that if I would not be obedient to the Lord's requirings,
He would take away His good Spirit from me again.
So I was in a strait; I was afraid of displeasing God, and afraid of displeasing man.
But at last I was charged by the Spirit with honoring man more than God.
For in my address to God I did use the plain language,^
footnote:[Most modern English speakers are unaware that the words "`you`" and
"`your`" were originally plural pronouns used only to address two or more people,
whereas "`thee`" and "`thou`" were used to address one person.
In the 1600's,
it became fashionable (as a means of showing honor or flattery) to use the
plural "`you`" or "`your`" in addressing people of higher social status,
while "`thee`" and "`thou`" were reserved for servants, children,
or people of lower social or economic position.
Early Friends stuck to what was then considered "`plain
language`" (using thee and thou to every single person,
and you and your to two or more),
rather than showing preferment by addressing certain individuals in the plural.]
but when I spoke to man or woman I would speak otherwise, or else they would be offended.
And I saw that the pride of man disdained to receive that language
from an inferior which he would freely give to the Almighty.
So this became a great cross to me,
and became an obstacle in the way of my soul's progress,
until I gave up to the Lord's requirings in this small thing.

These things I signify to you, dear friend, in great simplicity,
that you may see how the Lord leads out of the vain customs that are in the world,
not only in these things which I have mentioned, but also in many other things.
And likewise He leads into that humble,
self-denying way which Christ both taught and practiced when He was visible among men.
Indeed, Christ is the true Christians' pattern, and His Spirit their Leader.

I speak these things in truth and sincerity,
because I desire not to be misunderstood by you.
I am a single soul, wholly devoted to the Lord,
and so I do not plead for any outward form for form's sake;
neither do I plead for a particular sect or people, as a people.
For sadly, we have grown to be a mixed multitude,
much like the children of Israel when they were in the wilderness.
But this I may say to the praise and glory of God--the
principle that we make profession of is the very Truth,
namely, Christ in the male and in the female, the hope of glory.
And Christ, as you know, is the Way, the Truth, and the Life,
and no one comes to God but by Him.
So there is a remnant who, like Joshua and Caleb of old,
are true to the Lord their spiritual Leader, and follow Him faithfully,
and these stand in their testimonies against all dead formalities,
which are but worthless images when the living principle is withdrawn.
And as the Spirit of Jesus leads out of all vain
customs and traditions which are in the world,
and into the plain, humble, meek,
self-denying life and way in which Christ walked while He was visible among men,
I could wish all to follow the leadings of His Spirit herein,
that thereby they may truly confess Him before men.

But if it please the Almighty to accept souls without leading
them through such fiery trials as He brought me through,
or without requiring such things of them as He required of me,
far be it from me to judge that these have not
known the Lord or the indwelling of His love,
if the fruits of the Spirit of Jesus be clearly upon them.
For every tree is known by its fruits, and to our own master we must stand or fall.
But dear friend, as you well observed,
purification is a gradual work--I may say so by experience.
For when the old adversary could no longer draw
me out into vain talking and foolish jesting,
he then perplexed me with vain thoughts,
some of which were according to my natural disposition, and some of them quite contrary.
Oh, I cried mightily unto the Lord for power over vain thoughts,
for they were a great trouble to me!
And I stood in great fear lest one day or another I should fall by the hand of the enemy.
But the Lord spoke comfortably to my soul in His own words (which are left upon record),
"`Fear not, little flock,
it is your Father's good pleasure to give you the kingdom;`" and with these words,
the Lord gave me an evidence that my soul was one of that little flock.

Another time, when I was very low in my mind, these words sprang up with life and virtue:
"`Although you have lain among the pots, yet I will give you the wings of a dove,
covered with silver, and her feathers of yellow gold`" (Ps. 68:13). Oh,
it was wonderfully comfortable to me when the Holy
Spirit did bring a promise to my remembrance,
and gave me an evidence that it was my portion!
So I pondered concerning "`the wings of a dove,`" and I
thought they must be the wings of innocency,
whereby my soul might ascend unto God by prayer, meditation, and divine contemplation.
I took delight to pray in secret,
and to fast in secret from the outgoings of my mind as well as I could,
and my Heavenly Father (who sees and hears in secret) did reward me openly.
For then, when I went to meetings, I did not sit in darkness, dryness, and barrenness,
as I used to do in the time of my disobedience.
Instead, I reaped the benefit of the coming of Christ, who said,
"`The thief comes only to steal, and to kill, and to destroy;
I am come that they might have life, and have it more abundantly.`"
The thief had, in the time of my disobedience, stolen my soul from Jesus, who said,
"`Whoever loves father or mother, etc., or his own life more than me,
is not worthy of me.`"
So it had been with me, and I failed to reap the purpose of His coming for several years.
But in mercy He returned,
and afforded my bowed-down soul the enjoyment of His divine presence,
and was pleased to cause His love (which is the true life of the soul)
so to abound in my bosom in meetings that my cup did overflow.
And I was constrained, under a sense of duty, to kneel down in the congregation,
and confess to the goodness of God, and to pray to Him for the continuation of it,
and for power whereby I might be enabled to walk worthy of so great a favor, benefit,
and mercy, that I had received from His bountiful hand.

And I remember how after I had made public confession to the goodness of God,
my soul felt as if it had been in another world.
It was so enlightened and enlivened by divine love,
that I was in love with the whole creation of God,
and I saw everything to be good in its place.
I was shown how things ought to be kept in their proper places--that
the swine ought not to come into the garden,
and the clean beasts ought not to be taken into
the bed-chamber--and as it was in the outward,
so it ought to be in the inward and new creation.
So everything began to preach to me: the very fragrant herbs, and beautiful,
innocent flowers had a speaking voice to my soul,
and things seemed to have another relish with them than before.
The judgments of God were sweet to my soul,
and I was made at times to call others to come taste and see how good the Lord is,
and to exhort them to prove the Lord by an obedient, humble, innocent walking before Him.
Then they would see that He would pour out His spiritual blessings in so
plentiful a manner that there would not be room enough to contain them,
and the overflow would return to Him who is the Fountain with thanksgiving.
And at times I was made to warn people that they
should not provoke the Lord by disobedience.
For although He bears and suffers long (as He did with
the rebellious Israelites in the wilderness),
yet all shall know Him to be a God of justice and judgment,
and shall be made so to confess.

Thus, dear friend,
I have given you a plain but true account of my
qualification and call to the service of the ministry.
But it was several years before I came to a freed state, or to an even temper of mind.
For sometimes clouds would arise and interpose between my soul and the rising Sun,
and I was often brought down into the furnace.
But I found by experience that every time my soul was
brought down as into the furnace of affliction,
I did come up more clean and bright.
And even though the cloud did interpose between me and the rising Sun,
yet when the Sun of Righteousness did appear again, He brought healing under His wings,
and was nearer than before.
I express these things in simplicity,
as they were represented and made manifest to me in the morning of my days.

 I came to love to dwell with judgment, and I used to pray often saying, "`O Lord,
search me and try me, for You know my heart better than I know it!
I pray You let no deceitfulness or unrighteousness lodge therein,
but let Your judgments pass upon everything in me that is contrary to Your pure,
divine nature!`"
In this way my soul used to breathe to the Lord continually,
and hunger and thirst after a more full enjoyment of His presence.
And though He is a consuming fire to the corrupt nature of the old man,
yet my soul loved to dwell with Him.
I found that many sorts of corruptions endeavored to spring up in me again,
but I resigned my mind to the Lord,
with desires that He would feed me with food appropriate for me.
And this I can say by experience,
that the soul that is born of God does breathe to Him as constantly
by prayer as the newborn child does draw in and breathe out air.
Yes, in this same way the child of God draws in and breathes forth
the breath of life by which man was made a living soul to God.
But all who are still in the old man or fallen nature
know nothing of this pure and divine breathing,
for it is a mystery to them; yet the babe in Christ knows it to be true.
And although the children in our Father's family are of several ages, growths,
or statures (in regard to both strength and understanding),
yet this I have observed in all my travels,
that those who live to God continue in a state of breathing to Him while they are here,
and they continually hunger and thirst after a
more full enjoyment of His divine presence,
so that, though every day brings us nearer to the grave,
yet the soul may every day be brought into a greater divine union and communion with God.
It is a certain sign to me of the divine life and health of a
soul when I find it sweetly breathing unto the Lord,
and hungering and thirsting after His righteousness.
And indeed,
by one's manner of life it can be clearly seen and
easily known what sort of spirit does govern within him.
Oh it is true, that many will not believe these things,
nor try whether they be so or not, but instead are satisfied with the husk of religion.
But what will they do when the rudiments and beggarly elements of this world fall off,
and all our works must pass through the fire? My very soul mourns for them!
But we must press forward and leave them, if they will not arise out of their false rest.

Dear friend, as you well observe,
it is a great help for the soul to know its own corruptions,
and to understand from where it is fallen, that it may know how to return.
These things are very true, and the knowledge of them has been a great comfort to me,
and so have the experiences of the servants of the Lord
together with the testimonies left on record,
which are like way-marks to the spiritual traveler.
Truly we have a great privilege in and by these,
and above all in Christ our holy Pattern and heavenly Leader, who said,
"`My judgment is just, because I seek not my own will,
but the will of the Father who has sent me.`"
My soul prizes the knowledge of His footsteps, and the leading of His Spirit,
the Spirit of Truth, the Comforter, whom the Father has sent to lead us into all truth.
"`And oh,`" says my soul,
"`that we may follow the leadings of our unerring Guide
in all things that He may lead us into!`"
I have good cause to believe He will bring us through all
tribulations unto both the honor of God and our own comfort,
for the Lord has brought my soul through many trials, one after another,
as He has seen fit, some more of which I will hint at in what follows.

After my inward tribulation had abated, then the outward trials began;
and there were some of no small account,
which endeavored with all their might and cunning to
hinder the work of the Lord from prospering in me.
For just as Saul hunted David and sought to take away his natural life,
so these trials hunted my soul to take away its life, which it had in God;
yet all wrought together for my good.
I have often seen, and therefore may say,
that the Lord knows what is best for His children far better than we know for ourselves.
And so my enemies, instead of driving my soul away from God, drove it nearer to Him.
Yes, these trials caused me to prove the spirit which had the dominion of my mind,
and I found it to be the Spirit of Truth,
which the worldly and self-minded cannot receive;
for I found the nature of it to be harmless and holy, and to lead me to love my enemies,
to pity them and pray for them.
This love was my preservation;
and as I gave up in obedience to the operation and requiring of this meek Spirit,
it ministered such a peace to my soul as the world cannot give.

But still there was a disposition in me to please all,
which I found very hard to be weaned from, so as to stand single to God.
I found that when I feared man, I had nothing but anguish and sorrow;
and I would often walk alone and pour out my complaint to the Lord.
But after a long time, when the Lord had tried my faithfulness to Him as He saw fit,
one day as I was sitting in a meeting in silence,
waiting upon the Lord to know my strength renewed in Him,
this portion of Scripture was given to me: "`Comfort My people, says your God:
speak comfortably to Jerusalem, and cry unto her, that her warfare is accomplished,
that her iniquity is pardoned;
for she has received of the Lord's hand double for all her sins.`"
This brought great comfort to my soul, and I treasured it in my heart.
And I made this observation,
that from that time onward the Lord gave my soul (as the apostle Peter expresses it)
a more abundant entrance into the heavenly kingdom or New Jerusalem,
whose walls are salvation and her gates praise.
Indeed, my mind was brought into more stillness,
and troublesome thoughts were in a good degree expelled.
My outward enemies grew weary of their work and despaired of their hope,
the praise for which I freely (and in great
humility) offer up and ascribe to Almighty God;
for it was His own work to preserve me from so many strong temptations.

So after I had been favored with peace at home every way,
I was drawn by the Spirit of love to travel into the north of England.
On my journey my soul had many combats with the evil spirit, both when asleep and awake.
While I slept he tormented me as long as he could,
but an abundance of courage was given me to make war with him,
which much comforted my mind.
So I looked earnestly to the Lord to give me the
same victory over the devil when I was awake,
even as He had let me know when I was asleep.
The Spirit which led me forth was to me like the needle of a compass,
for so it pointed where I ought to go.
In those days I had certain manifestations of many things in dreams,
which did come to pass according to their significations.
Indeed, I was many times forewarned of my enemies,
and so was better equipped to guard against them.
I travelled in great fear and humility,
and the Lord was with me to His glory and my comfort,
and brought me home again in peace.

In the year 1697, in the sixth month, as I was sitting in the meeting in Gloucester,
England (which was then the place of my abode),
my mind was gathered into perfect stillness for a time.
My spirit then seemed as if it were carried away into America, and when it returned,
my heart was dissolved with the love of God, which flowed over the great ocean,
and I was constrained to kneel down and pray for the seed of God in America.
This concern never went out of my mind, day or night,
until I gave up to travel there in the love of God (which is a
love so universal that it reaches over land and sea). But when
I looked at the prospect with an eye of human reason,
it seemed a very strange and hard thing to me, for I knew nothing of the country,
nor anyone that dwelt there.
I reasoned much concerning my own unfitness, and when I let in such reasonings,
I felt nothing but death and darkness, and troubles attended my mind.
But when I resigned all to the Lord, and gave up in my mind to go,
then divine love sprang up in my heart,
and my soul was at liberty to worship the Lord as in the land of the living.

Thus I tried and proved the prospect of going to America in my own heart,
till at last these words ran through my mind with authority:
"`The fearful and unbelieving shall have their portion with the hypocrite,
in the lake that burns with fire and brimstone; which is the second death.`"
This brought a dread upon me,
so I then told my husband that I had a concern to go to America,
and asked him if he would be willing give me up.
He said he hoped it would not be required of me.
I told him it was, but that I should not go without his free consent,
which seemed a little hard to him at first.
Shortly thereafter, I was taken ill with a violent fever,
which brought me so weak that all who saw me thought I would not recover.
But being convinced that my day's work was not done,
my chief concern during the sickness was my going to America.
Some were troubled that I spoke openly about this, for they thought I would surely die,
and then some would have cause to speak reproachfully of me.
Others urged that, even if I were to recover,
my ship would be ready to sail long before I would be fit to go.
But I believed if they would only carry me and lay me down in the ship, I should be well;
for the Lord was very gracious to my soul in the time of my sickness,
and gave me a promise that His presence would go with me.
Then my husband was made very willing to give me up, for he said,
even if I were away for seven years,
it would be better than to have me taken from him forever.

So when at last all obstacles were removed, I sailed from Bristol in the ninth month,
1697, together with my companion Mary Rogers.
The dangers we were in at sea, the faith and courage the Lord gave to my soul,
and the remarkable things I witnessed before I returned out of America,
would be too much here to relate.
But this I may say:
I had such an evidence of being in my proper place that all fear was taken away.
Oh, it is good to trust in the Lord and be obedient to Him,
for His mercies endure forever!
Great indeed is the condescension and goodness of God to poor mankind,
and I may say to His praise that He has been with me through
many straits and difficulties (more than I can number),
and these have all wrought together for the good of my soul.
Yes, I have good cause to believe, that every son or daughter whom He receives,
He chastens, tries, and proves, and those who do not bear the chastisements of God,
do prove to be bastards and not sons.
But I may truly say, as one did of old,
"`It is good for me that I have been afflicted`" (Ps. 119:17),
and it is good to follow the leadings of the Spirit of God, as faithful Abraham did,
who was called the friend of God,
and who did not withhold his only son when the Lord called for him.
It is my belief the Lord will try His chosen ones as gold is tried,
and will yet refine them as gold is refined.
And what if He continues to bring us down into the furnace (in whatever way
it should please Him) until we are seven times refined? We shall then be the
better able to bear the impression of His image upon us in all that we do.

The testimony that Jesus bore to the scribe who
desired to follow Him is very true--"`Foxes have holes,
and the birds of the air have nests, but the Son of man has nowhere to lay His head.`"
Oh innocent Truth!
O plain, meek, humble Jesus!
Where does He find rest? Where does He reign without disturbance? Dear friend,
excuse my freedom with you, for the love of God constrains me,
and I do believe the Lord will show you yet further
what testimony you must bear for His name,
and what you must suffer for His sake, if you are faithful.
For trying times will come, and offenses will be given and taken,
but there is nothing that offends those who love the Lord Jesus above all.
Many murmured and were offended at Jesus when He told them the truth,
and many of His disciples left off from following Him.
Then said He to the twelve, "`Will you also go away?`" But Peter said, "`Lord,
to whom shall we go? You have the words of eternal life.
And we believe and know that You are that Christ, the Son of the living God.`"
So we see that God has always given the faithful to believe.
And now the Spirit of Truth has come, and does lead His followers into all truth.
Jesus Christ, who is one with His Spirit, was offered once to bear the sins of many,
and indeed has appeared again the second time without sin unto salvation.

Oh, surely the goodness of God has been very great to the children of men from age to age,
and from one generation to another, ever since the fall of our first parents.
The more my mind penetrates into it,
the more I am swallowed up in admiration of His condescension
and goodness through all His dispensations,
but above all in the manifestation of Jesus Christ, our holy Pattern and heavenly Leader.
O my soul, praise Him for the knowledge of His holy footsteps,
whom God has given for a light to us Gentiles,
and to be His salvation unto the ends of the earth!
Yes, He has given His Spirit to dwell in us, and has accepted our souls to dwell in Him!
O admirable goodness!
Shall we leave Him? He is the Word of eternal life,
and where else could we go? And in so far as any are followers of Jesus,
that far I desire to follow them and be one with them, and no farther.
And if any turn back from Him, and return into the sea out of which the beast arises,
and receive his mark, our Leader is not to be blamed.
For He holds forth His way, and causes His trumpet to be blown in Zion,
and an alarm to be sounded in His holy mountain.
Whosoever hears the sound of the trumpet and does not take warning,
his blood shall be upon his own head.
But he that takes warning shall deliver his own soul.
Oh great is the duty of the watchman!
And great is the kindness of God, as expressed in the 33rd chapter of Ezekiel!

O my dear friend, my heart is full of the goodness of the Lord.
But I must stop writing, lest I become too tedious to you; and indeed,
it might be accounted foolishness for me to
write after this manner to one in your station.
But I find a constraint thereto, and must commit it to your judgment, be it what it may.
And this I will assure you, my heart is plain; I mean what I speak,
and I find it safest to do so,
and to keep in humble obedience to the Lord in whatsoever He requires of me.
Yet I know the wisdom of God appears to be foolishness
in the eyes of the wise men of this world,
and we know that the wisdom of this world is foolishness with God,
and will prove so in the latter end to those poor souls who mightily esteem it.
But the souls of the righteous are in the hand of the Lord,
and though both their life and their death are
taken for misery in the sight of the unwise,
yet no torment shall touch them, and they shall rest in peace.

So in the love that is pure, does my soul greet you,
and remain your friend in true sincerity,

[.signed-section-signature]
Elizabeth Webb

[.asterism]
'''

__Elizabeth Webb was a respected minister in the Society of Friends who
travelled extensively in her service for the gospel.
As is mentioned in the above letter,
she crossed the Atlantic in 1697 to minister among the American colonies,
returning to England in 1699.
Her family then emigrated from England to Pennsylvania in 1700,
where she continued a minister until her death in 1726.
On at least one occasion (in 1710),
she returned to England in obedience to the Lord's requirings.
Little is known about this journey other than her
encounter with Anthony William Boehm in London,
to whom this letter is addressed.__
